# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='height_field',
            field=models.IntegerField(blank=True, default=600, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='width_field',
            field=models.IntegerField(blank=True, default=600, null=True),
        ),
    ]
