# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_personalinfo_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='interest',
            field=models.CharField(help_text='Sparate interests by comma', max_length=200, null=True),
        ),
    ]
